config/routes.rb
Rails.application.routes.draw do

  root 'home#index' #For Cognito login, if it happens

  get '/main', controller: 'main', action: 'index' # different from root because of login

  get '/library_items', controller: 'library_items', action: 'index'

  post '/library_items', controller: 'library_items', action: 'create', as: 'create_library_item'

  delete '/library_items/:datetime_created/:isbn', to: 'library_items#destroy', as: 'destroy_library_item'

  get 'library_items/:datetime_created/:isbn/edit', to: 'library_items#edit', as: 'edit_library_item'
  patch 'library_items/:datetime_created/:isbn' => 'library_items#update'

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  # before_action :require_login
  private

  def require_login
    #not yet implemented
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/index.html.erb
  <h1>Book Beep</h1>
  <main class="row">

    <!-- ERROR HANDLING HERE? -->
    <%if flash[:notice]%>
    <div class="flasher">
      <h4 id="notice"><%= flash[:notice] %></h4>
    </div>
    <%end%>

    <script type="text/javascript">littleBeep();</script>

    <div class="small-12 medium-12 large-12 column end">
      <div class="row main-form">
        <!-- PATH TO NEW ITEMS -->
        <h2>Add new items through Libris:</h2>
        <section class="small-12 medium-8 column end", id="libris-search-form">
          <%= form_tag(create_library_item_path, :method => "post") do %>
          <%= text_field_tag :isbn, params[:isbn], placeholder: "Enter ISBN to search/add from Libris #{params[:isbn]}" %>
          <%= submit_tag "Add New", :name => nil, class: "row"  %>
          <% end %>
        </section>
      </div>

      <!-- PATH TO VIEW ITEMS -->
      <div class="row main-form">
        <section class="small-12 medium-8 column", id="db-search-form">
          <h2>Search for items in the Book Beep database:</h2>
          <%if flash[:notice]%>
          <%end%>
          <%= form_tag(library_items_path, :method => "get") do %>
          <%= select_tag(:search_key, options_for_select([['ISBN', :isbn], ['Title', :title], ['Last Name', :creator_surname]], :isbn))%>
          <%= text_field_tag :search_value, params[:search_value], placeholder: "Search for #{params[:search_value]}" %>
          <%= submit_tag "Search", :name => nil  %>
          <% end %>
        </section>
      </div>
    </div>
  </main>

  <p>
    <%= link_to "List catalogue", library_items_path, class: "link-button" %>
  </p>

  <!-- List ten most popular media items -->
  <h2>- där ditt bibliotek sparas på molnet</h2>