config/routes.rb
Rails.application.routes.draw do

  root 'home#index' #For Cognito login, if it happens

  get '/main', controller: 'main', action: 'index' # different from root because of login

  get '/library_items', controller: 'library_items', action: 'index'

  post '/library_items', controller: 'library_items', action: 'create', as: 'create_library_item'

  delete '/library_items/:datetime_created/:isbn', to: 'library_items#destroy', as: 'destroy_library_item'

  get 'library_items/:datetime_created/:isbn/edit', to: 'library_items#edit', as: 'edit_library_item'
  patch 'library_items/:datetime_created/:isbn' => 'library_items#update'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
    <h1>Book Beep </h1>
    <div class="show-for-large-only">
      <h2>- där ditt bibliotek sparas på molnet</h2>
    </div>
    <p>This Rails app is using the Swedish database Libris and books with their ISBN to create a catalogue on DynamoDB.</p>

    <div>
      <p>Enter the portal to add items to the library catalogue using ISBN:
      <%= link_to "Book Beep Portal", main_path, method: :get, class: "link-button" %>
     </p>
    </div>
    <p></p>
    <h7>Search the royal library database elsewhere:</h7>
    <!-- BEGIN LIBRIS search box -->
    <div style="background: #191919 url(http://libris.kb.se/images/bg2_2.gif) bottom repeat-x; width: 80%;">
      <div style="background: url(http://libris.kb.se/images/main2_2.gif) no-repeat; width: 100%;">
        <form style="margin: 0; padding: 7px 0 11px 100px;" method="get" target="_blank" action="http://libris.kb.se/formatQuery.jsp?" accept-charset="UTF-8" onsubmit="window.open('http://libris.kb.se/formatQuery.jsp?SEARCH_ALL='+ encodeURIComponent(document.getElementById('LIBRIS_SEARCH2').value),'LIBRIS'); return false;">
          <fieldset style="margin: 0; padding: 0; border: none;">
            <legend style="margin: 0; padding: 0; display: none;">Sök i LIBRIS</legend>
            <div><input name="SEARCH_ALL" id="LIBRIS_SEARCH2" type="text" style="vertical-align: bottom; font-size: 11px; width: 70%;"/> <input type="submit" value="sök" style="vertical-align: bottom; cursor: pointer; font-size: 11px;"/></div>
          </fieldset>
        </form>
      </div>
    </div>
    <!-- END LIBRIS search box -->