config/routes.rb
Rails.application.routes.draw do

  root 'home#index' #For Cognito login, if it happens

  get '/main', controller: 'main', action: 'index' # different from root because of login

  get '/library_items', controller: 'library_items', action: 'index'

  post '/library_items', controller: 'library_items', action: 'create', as: 'create_library_item'

  delete '/library_items/:datetime_created/:isbn', to: 'library_items#destroy', as: 'destroy_library_item'

  get 'library_items/:datetime_created/:isbn/edit', to: 'library_items#edit', as: 'edit_library_item'
  patch 'library_items/:datetime_created/:isbn' => 'library_items#update'

end

app/models/library_item.rb
require 'aws-sdk'

class LibraryItem
  include ActiveModel::Validations
  # include Aws::Record
  # before action :create_client # if before action works for self-methods?

  validates :isbn, presence: true #, length: { is: (9 || 12) } # Primary Partition Key (Libris seems to have some unexpected length ISBNs)
  # validates :datetime_created, presence: true # Primary Sort Key
  validates :title, presence: true # Global Secondary Index

  attr_accessor :isbn, :datetime_created, :title, :creator_surname, :creator_first_name, :uri_id

  def initialize(info)
    @isbn = info['isbn']
    @datetime_created = info['datetime_created']
    @title = info['title']
    @creator_surname = info['creator_surname']
    @creator_first_name = info['creator_first_name']
    @uri_id = info['uri_id']
  end

# Method returns an instance of LibraryItem, if successful
# Method returns NIL if the search is unsuccessful/ISBN not found
  def self.libris_search(isbn)
    @library_item = LibrisWrapper.get_book(isbn)
    return @library_item
  end

  def self.all
    @library = []
    client = Aws::DynamoDB::Client.new # Config in aws.rb 
    table_name = "LibraryItems"

    results = client.scan({table_name: table_name})

    results.items.each do |listing|
      item = LibraryItem.new(listing)
      @library << item
    end
    return @library
  end

  # Method that will return a collection of library items depending on isbn, title or last name (partition key, GSIs)
  def self.get_media(info)
    client = Aws::DynamoDB::Client.new
    table_name = "LibraryItems"
    params = {}
    @library = [] # here is the return collection of instances of LibraryItem

    # STEP 1: SET UP THE PARAMS
    # First search for a specific item using the isbn AND datetime_created
    # if we know what item we want (we know the primary key)
    if info['isbn'] != nil && info['datetime_created'] != nil
      params = {
        table_name: table_name,
        key: {
        'isbn' => info['isbn'],
        'datetime_created' => info['datetime_created']
      }}
      response = client.get_item(params)
      if response.item != nil
        library_item = LibraryItem.new(response.item)
        @library << library_item
        # return @library # this is always of length one at this point
      else
        # return []
      end
      @library # Which is at length 1 or at [] at this point
    else # If we're looking for items
      # Second search for isbn only
      if info['isbn'] != nil # Partition key query
        params = {
          table_name: table_name,
          key_condition_expression: "isbn = :isbn", # because the db does not want to recompile the query if it already has it
          expression_attribute_values: {
            ":isbn" => info['isbn']
          }
        }
      end
      # # Third search for datetime_created only
      # if info[:datetime_created] != nil # Sort key query
      #   # NOT IMPLEMENTED
      #   # NO TESTS FOR THIS YET - should look the same as for info, but then we dont get a range
      #   # This is only used in case we are looking for a range, might be a much easier way to do this querywise
      #   # Return a collection within the date range
      # end
      # Forth search for GSI title
      if info['title'] != nil
        params = {
          table_name: table_name,
          index_name: 'title-upcase-index',
          select: 'ALL_PROJECTED_ATTRIBUTES',
          key_condition_expression: 'title_upcase = :title_upcase',
          expression_attribute_values: {
            ':title_upcase' => info['title'].mb_chars.upcase.to_s # UPCASE
          }
        }
        # puts "HERE HERE #{info['title']}"
      end
      # Fifth search for GSI creator_surname
      if info['creator_surname'] != nil
        params = {
          table_name: table_name,
          index_name: 'surname-upcase-index',
          select: 'ALL_PROJECTED_ATTRIBUTES',
          key_condition_expression: 'creator_surname_upcase = :creator_surname_upcase',
          expression_attribute_values: {
            ':creator_surname_upcase' => info['creator_surname'].mb_chars.upcase.to_s # UPCASE
          }
        }
      end
      # Check that params is not empty
      if params.empty?
        return @library # = [] # data.items = [] if nothing was found
      end
      # STEP 2: RUN QUERY
      begin
        data = client.query(params)
        if data.items.empty?
          return @library # = [] # data.items = [] if nothing was found
        end
        data.items.each { |listing|
          info['isbn'] = listing['isbn']
          info['datetime_created'] = listing['datetime_created']
          info['title'] = listing['title']
          info['creator_first_name'] = listing['creator_first_name']
          info['creator_surname'] = listing['creator_surname']
          info['uri_id'] = listing['uri_id']
          @library << LibraryItem.new(info)
        }
      rescue  Aws::DynamoDB::Errors::ServiceError => error
        puts "Unable to query table:"
        puts "#{error.message}"
        return @library
      end # query for collection/lists of items
    end #if
    return @library
  end

  # Returns nil for unsuccessful adding, and self for a successfully added object to DynamoDB
  def add_media
    #Create a new client to access DynamoDB
    client = Aws::DynamoDB::Client.new

    # Ensure valid item
    if @isbn == nil || @title == nil
      return nil
    end

    # Prepare params for inserting the instance into db
    item = {
      'isbn' => @isbn.to_i, # primary Partition key
      'title' => @title,
      'title_upcase' => @title.mb_chars.upcase.to_s,
      'datetime_created' => Time.now.to_datetime.strftime('%Q').to_i, # primary Sort key
    }
    if !@creator_first_name.nil?
      item['creator_first_name'] = @creator_first_name
    end
    if !@creator_surname.nil?
      item['creator_surname'] = @creator_surname
      item['creator_surname_upcase'] = @creator_surname.mb_chars.upcase.to_s
    end
    if !@uri_id.nil?
      item['uri_id'] = @uri_id
    end

    params = {
      table_name: "LibraryItems",
      item: item
    }

      # Accessing DynamoDB to add the new item
      begin
        client.put_item(params) # add new item into DynamoDB
        return self
      rescue  Aws::DynamoDB::Errors::ServiceError => error
        puts "Unable to add item:"
        puts "#{error.message}"
        return nil
      end
  end

  def destroy_media
    client = Aws::DynamoDB::Client.new
    params = {
      table_name: "LibraryItems",
      key: {
        'isbn' => self.isbn,
        'datetime_created' => self.datetime_created
      }
    }
    client.delete_item(params)
  end

# @todo test test
  # QUERY IF ISBN ALREADY EXISTS IN DATABASE
  # return list of objects, if any, or []
  def check_copies
  #   # Set up query
  #   query = {
  #     table_name: "LibraryItems",
  #     key_condition_expression: "isbn = :isbn",
  #     expression_attribute_values: {
  #       ":isbn" => item['isbn']
  #     }
  #   }
  #   # Run query
  #   begin
  #     results = dynamodb.query(query)
  #   rescue  Aws::DynamoDB::Errors::ServiceError => error
  #     puts "#add_media test: Unable to query table:"
  #     puts "#{error.message}"
  #   end
  #
  #
  end

private

  # def create_client
  #   @client = Aws::DynamoDB::Client.new unless @client
  # end

end

app/controllers/library_items_controller.rb
class LibraryItemsController < ApplicationController
  before_action :dynamodb_setup #, :require_login

  def index
    # Build query params from search
    if params[:search_key] == 'isbn'
      @info[params[:search_key]] = params[:search_value].to_i
    else
      @info[params[:search_key]] = params[:search_value]
    end

    # For when the List all button is pressed
    unless params[:search_key] == 'isbn' || params[:search_key] == 'title' || params[:search_key] == 'creator_surname'
      items = LibraryItem.all
    else
      items = LibraryItem.get_media(@info)
    end

    if items.empty?
      flash[:notice] = 'Book Beep returned no items for this search'
      redirect_to main_path
      return
    end

    #Sort the media (not tested)
    sorted_items = items.sort_by { |item|
      item.datetime_created
    }
    @library_items = sorted_items.reverse

  end

  # Redirect to here from main#index if the add new item form is filled in
  def create
    # TODO: Add text ('one') to number ('1') conversion
    isbn = params['isbn'].gsub(/[^0-9,.]/, "").to_i
    # Check for no/invalid entry
    if isbn%100000000 < 1
      flash[:notice] = "This is not a valid ISBN"
      redirect_to main_path
      return
    end
    @library_item = LibraryItem.libris_search(isbn)

    if @library_item.nil?
      flash[:notice] = "This ISBN was not found in Libris: #{params['isbn']}"
      redirect_to main_path # what is the difference between render/redirect?
      return
    end

    if @library_item.valid?
      #SUCCESS
      @library_item = @library_item.add_media
      if @library_item.nil?
        flash[:notice] = "The item could not be added to Book Beep."
        redirect_to main_path
        return
      end
      flash[:notice] = "BEEP! '#{@library_item.title }' was successfully added to Book Beep"
      params[:search_key] = 'isbn'
      params[:search_value] = @library_item.isbn.to_s
      redirect_to library_items_path(params)
      return
    else
      #FAILURE
      flash[:notice] = "This item is not valid to enter by this method"
      redirect_to main_path
      return
    end
  end

  def destroy
    #PARAMS FOR ONE ITEM SEARCH - COMPLETE PRIMARY KEY NEEDED
    @info['isbn'] = params['isbn'].to_i
    @info['datetime_created'] = params['datetime_created'].to_i
    # Get the item to be destroyed
    @library_item = LibraryItem.get_media(@info)[0]
    @info['title'] = @library_item.title
    @library_item.destroy_media # do I need to do a if save! kindofthing here?
    # Does this list the whole database because of params @todo
    flash[:notice] = "Deleted item from database: '#{@info['title']}'"
    redirect_to library_items_path(params) #WEAK PARAMS
  end

  def update
    # @info['isbn'] = params['isbn'].to_i
    # @info['datetime_created'] = params['datetime_created'].to_i

    flash[:notice] = 'Update is not yet implemented'
    redirect_to library_items_path
  end

  def edit
    flash[:notice] = 'Edit is not yet implemented'
    redirect_to library_items_path
  end



  private

  def index_params
    # return params.permit(@info)
    # return params.permit(:isbn, :datetime_created, :creator_first_name, :creator_surname, :title)
    return params.permit(:search_key, :search_value, :isbn, :creator_surname, :title)
  end

  def dynamodb_setup
    @client = Aws::DynamoDB::Client.new
    @info = {table_name: "LibraryItems"}

  end
end

app/helpers/library_items_helper.rb
module LibraryItemsHelper

# Controller had no access, and it's not tested anyhow
  def sorting_by_date(items)
    sorted_items = items.sort_by { |item|
      item.datetime_created
    }
    return sorted_items.reverse
  end

  def params_to_text(search_param)
    if params[:search_key] == 'creator_surname'
      return 'Author'
    elsif params[:search_key] == 'title'
      return 'Title'
    else
      return 'ISBN'
    end
  end

end

app/views/library_items/_big_table.html.erb
  <table class="hide-for-small-only large-item-list">
    <thead>
      <tr>
        <th scope="col">ISBN</th>
        <th scope="col">Title</th>
        <th scope="col">Creator</th>
        <th class="date-column", scope="col">Date Added</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @library_items.each do |listing| %>
      <tr>
        <td scope="row">
          <%= "#{listing.isbn.to_i}" %>
        </td>
        <td>
          <% if !listing.uri_id.nil? %>
          <%= link_to "#{listing.title}", listing.uri_id, target: "_blank" %>
          <% else %>
          <%= "#{listing.title}" %>
          <% end %>
        </td>
        <% if listing.creator_surname || listing.creator_first_name %>
        <td>
          <% if listing.creator_first_name %>
          <%= "#{listing.creator_first_name}" %>
          <% end %>
          <% if listing.creator_surname %>
          <%= "#{listing.creator_surname}" %>
          <% end %>
        </td>
        <% end %>
        <td>
          <%= "#{convert_ms_to_time(listing.datetime_created)}" %>
        </td>
        <td>
          <%= button_to "Delete", destroy_library_item_path('isbn': listing.isbn.to_i, 'datetime_created': listing.datetime_created.to_i), method: :delete, data: { confirm: "Are you sure that this item must be deleted? (#{listing.title})" }, class: "alert button" %>
        </td>
        <td>
          <%= button_to "Edit", edit_library_item_path('isbn': listing.isbn.to_i, 'datetime_created': listing.datetime_created.to_i), method: :get, class: "solid_button" %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/library_items/_small_table.html.erb
  <table class="show-for-small-only small-item-list">
    <thead>
      <tr>
        <th scope="col">Date Added</th>
        <th scope="col">Title / Creator</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @library_items.each do |listing| %>
      <tr>
        <td scope="row">
          <%= "#{convert_ms_to_short_time(listing.datetime_created)}" %>
        </td>
        <td>
          <%= "#{listing.title} / #{listing.creator_surname}" %>
        </td>
        <td>
          <%= button_to "Delete", destroy_library_item_path('isbn': listing.isbn.to_i, 'datetime_created': listing.datetime_created.to_i), method: :delete, data: { confirm: "Are you sure that this item must be deleted? (#{listing.title})" }, class: "alert button" %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/library_items/index.html.erb
<%= link_to "Library Main", main_path, class: 'link-button'  %>

<!-- ERROR HANDLING HERE? -->
<%if flash[:notice]%>
<div class="flasher row">
  <h3 id="notice"><%= flash[:notice] %></h3>
</div>
<!-- Currently the only flash notice here is for adding data to DynamoDB -->
<script type="text/javascript">bigBeep();</script>
<%end%>

<article class="row">
  <section class="small-12 medium-10 large-10 column end">
    <h2>Search results for <%= "(#{params_to_text(params[:search_key])}): #{params[:search_value]}" %></h2>

    <div class="hide-for-small-only">
      <%= render partial: "big_table" %>
    </div>

    <div class="show-for-small-only">
      <%= render partial: "small_table" %>
    </div>
  </section>
</article>